# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb0c084679e911722cc5fc5e8cd9a97918475a86c6ea7fad0ed5061abac2487148475dd0b808edd2d12e82489b6759ecef8d215a1269e6ae017b418375dd8309

test:
  secret_key_base: 656c185a0fcf6a2fc792f647b9ca7e513a9902aaa3cbbbd92fede9b03afb14d9702d33dae9dff04bfe6233c9f541a1cccc4573f339502243c08ab00215ef634c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
